on:
  push:
  pull_request:

jobs:
  rust:
    name: Lint Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --workspace

  rust-msrv:
    name: Build-test MSRV (1.74) with minimal crate dependencies
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@nightly
      - name: Generate minimal-version dependencies
        run: cargo -Zminimal-versions generate-lockfile
      - uses: dtolnay/rust-toolchain@1.74.0
      - name: Cargo check
        run: cargo check --workspace --all-targets
      - name: Mini test
        run: cargo run --example info
      - uses: actions/upload-artifact@v4
        with:
          name: info-${{ matrix.os }}
          path: info.txt